# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-dustinwicker-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-169870213-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'posts.html'}
# - {name: 'Teaching Resources', path: 'menu', url: 'teaching_resources.html'}
- {name: 'Testimonials', path: 'menu', url: 'testimonials.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/dustinwicker'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/dustin-wicker/'}
- {icon: 'envelope', link: 'mailto:dustinlwicker@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
